version: "3.8"
services:
  auth-service:
    build: ./auth_service
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  postgres:
    build: ./database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres   
      POSTGRES_PASSWORD: my_password 
      POSTGRES_DB: fc2           
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: